### PR TITLE
Patches from our fork

### PR DESCRIPTION
**Pull request by vikraman**
I tried to cherry-pick some of my commits, but ran into conflicts. This diff looks good though.

### CODE REVIEW

**Comment by vikraman** [comment]
Sorry, it's wrong.

**Comment by vikraman** [comment]
Updated. I think we started from an earlier commit in your repo, so it was out of date and led to conflicts.

**Comment by vikraman** [comment]
Ok, I dropped the other changes, and just have the loop fix here.

**Comment by gcampax** [comment]
Ok, merged, I'll squash for the next iteration of the patch on phabricator

**Pull request merged**
